controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    base_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

base_controller:
  ros__parameters:
    # URDF 상 좌측/우측 조인트 이름이 아래와 같이 정의되어 있다고 가정합니다.
    left_wheel_names: ["front_left_wheel_joint", "rear_left_wheel_joint"]
    right_wheel_names: ["front_right_wheel_joint", "rear_right_wheel_joint"]
    
    # 양쪽에 2개씩의 바퀴가 있음
    wheels_per_side: 2

    write_op_modes: ["motor_controller"]

    # URDF에서 추출한 값:
    # 좌우 바퀴 간(트랙) 거리: 약 0.58306 m
    # 바퀴 반지름: 약 0.16459 m
    wheel_separation: 0.58306
    wheel_radius: 0.16459

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

    position_feedback: true
    open_loop: false
    enable_odom_tf: true

    cmd_vel_timeout: 0.5
    publish_limited_velocity: false
    velocity_rolling_window_size: 10
    use_stamped_vel: false

    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 5.0
    linear.x.min_velocity: -5.0
    linear.x.max_acceleration: 5.0
    linear.x.min_acceleration: -5.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 5.0
    angular.z.min_velocity: -5.0
    angular.z.max_acceleration: 5.0
    angular.z.min_acceleration: -5.0